browser = edge

loginurl = https://javabykiran.com/liveproject/index.html

registerurl = https://javabykiran.com/liveproject/pages/examples/register.html

adduserurl = https://javabykiran.com/liveproject/pages/examples/add_user.html
